# Generated by Django 4.2.6 on 2023-10-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_accept',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_reject',
            field=models.CharField(default='', max_length=2),
        ),
    ]
