# Generated by Django 4.2.6 on 2023-10-15 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboardapp', '0003_alter_comment_options_alter_post_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_confirmation', models.CharField(default='', max_length=20)),
                ('code_confirmation_type', models.IntegerField(default=0)),
                ('code_confirmation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
