# Generated by Django 4.2.6 on 2023-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0005_codeconfirmation_code_confirmation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeconfirmation',
            name='code_confirmation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
