# Generated by Django 4.2.6 on 2023-10-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0006_alter_codeconfirmation_code_confirmation_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeconfirmation',
            name='code_confirmation_user',
        ),
        migrations.AddField(
            model_name='codeconfirmation',
            name='code_confirmation_email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
