# Generated by Django 4.2.6 on 2023-10-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboardapp', '0007_remove_codeconfirmation_code_confirmation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeconfirmation',
            name='code_confirmation_user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
