# Generated by Django 4.2.6 on 2023-10-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0008_codeconfirmation_code_confirmation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeconfirmation',
            name='code_confirmation_user',
        ),
    ]
