# Generated by Django 4.2.6 on 2023-10-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0009_remove_codeconfirmation_code_confirmation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
