# Generated by Django 4.2.6 on 2023-10-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0010_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=0, upload_to='images'),
        ),
    ]
