# Generated by Django 4.2.6 on 2023-10-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0011_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bboardapp.category', verbose_name='Категория'),
        ),
    ]
