# Generated by Django 4.2.6 on 2023-10-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0012_remove_post_post_category_alter_post_post_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
