# Generated by Django 4.2.6 on 2023-10-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0013_delete_postcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bboardapp.category', verbose_name='Категория'),
        ),
    ]
