# Generated by Django 4.2.6 on 2023-10-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0015_post_post_video_alter_post_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='video')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_video',
            field=models.FileField(upload_to='video'),
        ),
    ]
