# Generated by Django 4.2.6 on 2023-10-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0016_uploadvideo_alter_post_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_video',
            field=models.CharField(max_length=500, verbose_name='Ссылка на видео'),
        ),
    ]
