# Generated by Django 4.2.6 on 2023-10-28 19:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboardapp', '0017_alter_post_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('news_title', models.CharField(max_length=124, verbose_name='Заголовок')),
                ('news_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полный текст новости')),
                ('news_image', models.ImageField(upload_to='images')),
                ('news_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboardapp.author', verbose_name='Автор')),
            ],
        ),
    ]
